site_name: Staging Documentation
site_url: htthps://staging.docs.infrastructureautomation.io
theme:
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.suggest
    - search.share




  name: material
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - blog
  - search


markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition
  - def_list
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true